### ISSUE TITLE
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101 运行时报错，请教一下作者，感谢！

### ISSUE THREAD

**Issue by sanbens** [bytedance/WMP#17]
感谢作者们的杰出工作，我想问一下我运行的时候出现以下报错，可能的原因是？已经用preview3了。
我的显卡配置是：sanbens@sanbens-9960x:~$ nvidia-smi
Wed Nov 12 16:30:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.190                Driver Version: 570.190        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:01:00.0 Off |                  N/A |
| 41%   49C    P0            115W /  250W |     334MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  |   00000000:11:00.0  On |                  N/A |
| 32%   35C    P8             32W /  250W |     707MiB /  24576MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        On  |   00000000:C1:00.0 Off |                  N/A |
| 42%   27C    P8             18W /  250W |     138MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090        On  |   00000000:E1:00.0 Off |                  N/A |
| 30%   37C    P0            110W /  250W |    1661MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

输出为：[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] Gym cuda error: invalid device ordinal: ../../../source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 991
/home/sanbens/miniconda3/envs/WMP/lib/python3.8/site-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
'train_cfg' provided -> Ignoring 'name=a1_amp'
Begin construct world model
Encoder CNN shapes: {'image': (64, 64, 1)}
Encoder MLP shapes: {'prop': (33,)}
cnn outdim 4096
mlp outdim 1024
total outdim: 5120
Decoder CNN shapes: {'image': (64, 64, 1)}
Decoder MLP shapes: {'prop': (33,)}
Optimizer model_opt has 25236129 variables.
Finish construct world model
Actor MLP: Sequential(
  (0): Linear(in_features=70, out_features=256, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=256, out_features=128, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=128, out_features=64, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=64, out_features=12, bias=True)
)
Critic MLP: Sequential(
  (0): Linear(in_features=317, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=1, bias=True)
)
Loaded 10.0s. motion from datasets/mocap_motions/hop1.txt.
Loaded 10.0s. motion from datasets/mocap_motions/trot1.txt.
Loaded 10.0s. motion from datasets/mocap_motions/trot2.txt.
Loaded 10.0s. motion from datasets/mocap_motions/hop2.txt.
Preloading 2000000 transitions
Finished preloading
*** Can't create empty tensor
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 65, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 58, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/sanbens/Code/WMP/rsl_rl/runners/wmp_runner.py", line 254, in learn
    obs, privileged_obs, rewards, dones, infos, reset_env_ids, terminal_amp_states = self.env.step(
  File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 180, in step
    reset_env_ids, terminal_amp_states = self.post_physics_step()
  File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 292, in post_physics_step
    self.update_depth_buffer()
  File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 241, in update_depth_buffer
    depth_image = self.process_depth_image(depth_image, i)
  File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 212, in process_depth_image
    depth_image += self.cfg.depth.dis_noise * 2 * (torch.rand(1)-0.5)[0]
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'

**Comment by hanglai** [comment]
你好！看上去是isaacgym获取深度图失败了，如果是有图形界面的服务器可以先跑一下isaacgym/python/examples/1080_balls_of_solitude.py，看看是否能正常渲染画面，如果是无图形界面的服务器，可以参考官方文档：https://docs.robotsfan.com/isaacgym/programming/graphics.html里的方法调用相机试试。如果无法调用相机，可以尝试安装一些库：
sudo apt-get update
sudo apt-get install libgl1-mesa-dri
sudo apt-get install -y libegl1 libgl1 libgles2
还是不行的话建议试试重装显卡驱动

**Comment by findasoulmate** [comment]
在无可视化的服务器，让人奇怪的是，最开始我可以在cuda:0上运行，在cuda:1等等都运行不了，后来我尝试别的显卡驱动，我上遇到了与你相同的问题。。。然后再在cuda:0上也运行不了。后来恢复显卡驱动最初的版本，还是出现这个错误：
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101
[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101

哈哈，有时真的挺无语的

**Comment by hanglai** [comment]
是的，在cuda:1上确实会出现类似的错误，可能是isaacgym渲染的问题，建议在cuda:0上先试试

**Comment by Crazy-Wxs** [comment]
> 感谢作者们的杰出工作，我想问一下我运行的时候出现以下报错，可能的原因是？已经用preview3了。 我的显卡配置是：sanbens@sanbens-9960x:~$ nvidia-smi Wed Nov 12 16:30:25 2025 +-----------------------------------------------------------------------------------------+ | NVIDIA-SMI 570.190 Driver Version: 570.190 CUDA Version: 12.8 | |-----------------------------------------+------------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+========================+======================| | 0 NVIDIA GeForce RTX 3090 On | 00000000:01:00.0 Off | N/A | | 41% 49C P0 115W / 250W | 334MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 1 NVIDIA GeForce RTX 3090 On | 00000000:11:00.0 On | N/A | | 32% 35C P8 32W / 250W | 707MiB / 24576MiB | 24% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 2 NVIDIA GeForce RTX 3090 On | 00000000:C1:00.0 Off | N/A | | 42% 27C P8 18W / 250W | 138MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 3 NVIDIA GeForce RTX 3090 On | 00000000:E1:00.0 Off | N/A | | 30% 37C P0 110W / 250W | 1661MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+
> 
> 输出为：[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] Gym cuda error: invalid device ordinal: ../../../source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 991 /home/sanbens/miniconda3/envs/WMP/lib/python3.8/site-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] 'train_cfg' provided -> Ignoring 'name=a1_amp' Begin construct world model Encoder CNN shapes: {'image': (64, 64, 1)} Encoder MLP shapes: {'prop': (33,)} cnn outdim 4096 mlp outdim 1024 total outdim: 5120 Decoder CNN shapes: {'image': (64, 64, 1)} Decoder MLP shapes: {'prop': (33,)} Optimizer model_opt has 25236129 variables. Finish construct world model Actor MLP: Sequential( (0): Linear(in_features=70, out_features=256, bias=True) (1): ELU(alpha=1.0) (2): Linear(in_features=256, out_features=128, bias=True) (3): ELU(alpha=1.0) (4): Linear(in_features=128, out_features=64, bias=True) (5): ELU(alpha=1.0) (6): Linear(in_features=64, out_features=12, bias=True) ) Critic MLP: Sequential( (0): Linear(in_features=317, out_features=512, bias=True) (1): ELU(alpha=1.0) (2): Linear(in_features=512, out_features=256, bias=True) (3): ELU(alpha=1.0) (4): Linear(in_features=256, out_features=128, bias=True) (5): ELU(alpha=1.0) (6): Linear(in_features=128, out_features=1, bias=True) ) Loaded 10.0s. motion from datasets/mocap_motions/hop1.txt. Loaded 10.0s. motion from datasets/mocap_motions/trot1.txt. Loaded 10.0s. motion from datasets/mocap_motions/trot2.txt. Loaded 10.0s. motion from datasets/mocap_motions/hop2.txt. Preloading 2000000 transitions Finished preloading *** Can't create empty tensor Traceback (most recent call last): File "legged_gym/scripts/train.py", line 65, in train(args) File "legged_gym/scripts/train.py", line 58, in train ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True) File "/home/sanbens/Code/WMP/rsl_rl/runners/wmp_runner.py", line 254, in learn obs, privileged_obs, rewards, dones, infos, reset_env_ids, terminal_amp_states = self.env.step( File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 180, in step reset_env_ids, terminal_amp_states = self.post_physics_step() File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 292, in post_physics_step self.update_depth_buffer() File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 241, in update_depth_buffer depth_image = self.process_depth_image(depth_image, i) File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 212, in process_depth_image depth_image += self.cfg.depth.dis_noise * 2 * (torch.rand(1)-0.5)[0] TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'

您好 这个问题您后来是怎么解决的

**Comment by an1iu** [comment]
> 感谢作者们的杰出工作，我想问一下我运行的时候出现以下报错，可能的原因是？已经用preview3了。 我的显卡配置是：sanbens@sanbens-9960x:~$ nvidia-smi Wed Nov 12 16:30:25 2025 +-----------------------------------------------------------------------------------------+ | NVIDIA-SMI 570.190 Driver Version: 570.190 CUDA Version: 12.8 | |-----------------------------------------+------------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+========================+======================| | 0 NVIDIA GeForce RTX 3090 On | 00000000:01:00.0 Off | N/A ||0 NVIDIA GeForce RTX 3090 开启 |00000000：01：00.0 关闭 |无 | | 41% 49C P0 115W / 250W | 334MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 1 NVIDIA GeForce RTX 3090 On | 00000000:11:00.0 On | N/A ||1 台 NVIDIA GeForce RTX 3090 开启 |00000000：11：00.0 上 |无 | | 32% 35C P8 32W / 250W | 707MiB / 24576MiB | 24% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 2 NVIDIA GeForce RTX 3090 On | 00000000:C1:00.0 Off | N/A ||2 NVIDIA GeForce RTX 3090 开启 |00000000：C1：00.0 关闭 |无 | | 42% 27C P8 18W / 250W | 138MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 3 NVIDIA GeForce RTX 3090 On | 00000000:E1:00.0 Off | N/A | | 30% 37C P0 110W / 250W | 1661MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+
> 
> 输出为：[Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 rgbImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在深度图像缓冲区错误 101 上失败 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 segmentationImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在光流缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 rgbImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在深度图像缓冲区错误 101 上失败 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 segmentationImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在光流缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 rgbImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在深度图像缓冲区错误 101 上失败 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 segmentationImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在光流缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on rgbImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 rgbImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on depthImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在深度图像缓冲区错误 101 上失败 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on segmentationImage buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在 segmentationImage 缓冲区上失败，错误 101 [Error] [carb.gym.plugin] cudaExternamMemoryGetMappedBuffer failed on optical flow buffer with error 101[错误][carb.gym.plugin] cudaExternamMemoryGetMappedBuffer 在光流缓冲区上失败，错误 101 [Error] [carb.gym.plugin] Gym cuda error: invalid device ordinal: ../../../source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 991 [Error] [carb.gym.plugin] Gym cuda error: invalid device ordinal: .. /.. /.. /source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 991 /home/sanbens/miniconda3/envs/WMP/lib/python3.8/site-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)/home/sanbens/miniconda3/envs/WMP/lib/python3.8/site-packages/torch/functional.py：512： UserWarning： torch.meshgrid： 在即将发布的版本中，将需要传递索引参数。（内部触发于....../aten/src/ATen/native/TensorShape.cpp：3587.） return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]返回 _VF.meshgrid（tensors， **kwargs） # 类型：忽略[attr-defined] 'train_cfg' provided -> Ignoring 'name=a1_amp'提供“train_cfg”，->忽略“name=a1_amp” Begin construct world model Encoder CNN shapes: {'image': (64, 64, 1)} Encoder MLP shapes: {'prop': (33,)} cnn outdim 4096 mlp outdim 1024 total outdim: 5120 Decoder CNN shapes: {'image': (64, 64, 1)} Decoder MLP shapes: {'prop': (33,)} Optimizer model_opt has 25236129 variables. Finish construct world model Actor MLP: Sequential(  演员 MLP：连续剧（ (0): Linear(in_features=70, out_features=256, bias=True)（0）：线性（in_features=70，out_features=256，偏置=真） (1): ELU(alpha=1.0) (2): Linear(in_features=256, out_features=128, bias=True)（2）：线性（in_features=256，out_features=128，偏置=真） (3): ELU(alpha=1.0) (4): Linear(in_features=128, out_features=64, bias=True)（4）：线性（in_features=128，out_features=64，偏置=真） (5): ELU(alpha=1.0) (6): Linear(in_features=64, out_features=12, bias=True)（6）：线性（in_features=64，out_features=12，偏置=真） ) Critic MLP: Sequential(  评论家 MLP：连贯（ (0): Linear(in_features=317, out_features=512, bias=True)（0）：线性（in_features=317，out_features=512，偏置=真） (1): ELU(alpha=1.0) (2): Linear(in_features=512, out_features=256, bias=True)（2）：线性（in_features=512，out_features=256，偏置=真） (3): ELU(alpha=1.0) (4): Linear(in_features=256, out_features=128, bias=True)（4）：线性（in_features=256，out_features=128，偏置=真） (5): ELU(alpha=1.0) (6): Linear(in_features=128, out_features=1, bias=True)（6）：线性（in_features=128， out_features=1， 偏置=真） ) Loaded 10.0s. motion from datasets/mocap_motions/hop1.txt.装填 10.0。来自数据集/mocap_motions/hop1.txt 的运动。 Loaded 10.0s. motion from datasets/mocap_motions/trot1.txt.装填 10.0。来自数据集/mocap_motions/trot1.txt 的运动。 Loaded 10.0s. motion from datasets/mocap_motions/trot2.txt.装填 10.0。来自数据集/mocap_motions/trot2.txt 的运动。 Loaded 10.0s. motion from datasets/mocap_motions/hop2.txt.装填 10.0。来自数据集/mocap_motions/hop2.txt 的运动。 Preloading 2000000 transitions Finished preloading *** Can't create empty tensor无法生成空张量 Traceback (most recent call last):追溯（最近一次通话）： File "legged_gym/scripts/train.py", line 65, in train(args)  列车（ARGS） File "legged_gym/scripts/train.py", line 58, in train ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)ppo_runner.learn（num_learning_iterations=train_cfg.runner.max_iterations， init_at_random_ep_len=True） File "/home/sanbens/Code/WMP/rsl_rl/runners/wmp_runner.py", line 254, in learn obs, privileged_obs, rewards, dones, infos, reset_env_ids, terminal_amp_states = self.env.step(obs， privileged_obs， rewards， dones， information， reset_env_ids， terminal_amp_states = self.env.step（ File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 180, in step reset_env_ids, terminal_amp_states = self.post_physics_step()reset_env_ids，terminal_amp_states = self.post_physics_step（） File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 292, in post_physics_step self.update_depth_buffer() File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 241, in update_depth_buffer depth_image = self.process_depth_image(depth_image, i) File "/home/sanbens/Code/WMP/legged_gym/envs/base/legged_robot.py", line 212, in process_depth_image depth_image += self.cfg.depth.dis_noise * 2 * (torch.rand(1)-0.5)[0]depth_image += self.cfg.depth.dis_noise * 2 * （torch.rand（1）-0.5）[0] TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'TypeError：+=不支持的作数类型：'NoneType'和'Tensor'

我也遇到了同样的问题，请问是如何解决的？

**Comment by hanglai** [comment]
你好，这个问题看上去是深度图获取失败，建议先试试isaacgym自带的获取图像的example，在isaacgym/python/example中有设置相机、获取图像的代码。如果example获取图像也有问题，可能是显卡驱动或者vulkan相关的包的问题，可以试试：
sudo sh ./NVIDIA-Linux-x86_64-$version.run --no-kernel-module -b -q -e --ui=none
sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils -y
sudo apt install -y libgl1 libegl1 libglx0 libxext6

**Comment by RX-105** [comment]
我也遇到了这个问题，环境是对齐了的。我调试完发现是cuda设备id和vulkan设备id不匹配的问题，我的服务器有四张显卡，指定CUDA_VISIBLE_DEVICES=0和sim_device=cuda:0时，这张卡的vulkan device id是3，设备顺序号错误，导致了深度图像获取失败。我用了CUDA_VISIBLE_DEVICES=3,2,1,0来重排顺序，算是解决了这个问题，不过要是能在训练脚本里增加一段设备号匹配的代码就好了。

**Comment by RX-105** [comment]
我这里似乎就是多显卡设备号匹配问题，写了一个小脚本替换了原有的训练脚本，在我这里可以解决问题。你感兴趣的话我可以发你一份。
